project:
  type: website

website:
  title: "Naveen Kumar Pandey"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: "Home"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

execute:
  freeze: auto



