project:
  type: website
  output-dir: _site

website:
  title: "Naveen Kumar Pandey"
  site-url: https://nav13n.github.io
  repo-url: https://github.com/nav13n/nav13n.github.io
  navbar:
    background: none
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog/index.qmd
      # - icon: fa-brands fa-github
      #   href: https://github.com/nav13n
      # - icon: fa-brands fa-x-twitter
      #   href: https://x.com/naveenpnd
      # - icon: fa-brands fa-linkedin-in
      #   href: https://www.linkedin.com/in/nav13n
  page-footer:
    right: |
      © 2024 Naveen Kumar Pandey


format:
  html:
    theme:
      light: [default, custom-light.scss]
      dark: [default, custom-dark.scss]
    mainfont: "Figtree"
    monofont: "Fira Code"
    code-copy: true
    code-overflow: wrap
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">